name: Metrics
on:
  push:
    branches: [ main, master ]
    paths-ignore:
      - '*.svg'
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

permissions:
  contents: write
  issues: write

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        name: Classic metrics
        with:
          user: fallgozxtest
          template: classic
          filename: metrics-classic.svg
          output_action: commit
          committer_branch: main
          committer_message: 'chore: update classic metrics [Skip GitHub Action]'
          token: ${{ secrets.METRICS_TOKEN }}
      - uses: lowlighter/metrics@latest
        name: Languages & habits
        with:
          user: fallgozxtest
          template: classic
          filename: metrics-languages.svg
          plugin_languages: yes
          plugin_languages_indepth: yes
          plugin_habits: yes
          plugin_habits_charts: yes
          output_action: commit
          committer_branch: main
          committer_message: 'chore: update languages metrics [Skip GitHub Action]'
          token: ${{ secrets.METRICS_TOKEN }}
      - uses: lowlighter/metrics@latest
        name: Isometric calendar
        with:
          user: fallgozxtest
          template: classic
          filename: metrics-calendar.svg
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          output_action: commit
          committer_branch: main
          committer_message: 'chore: update calendar metrics [Skip GitHub Action]'
          token: ${{ secrets.METRICS_TOKEN }}
      - uses: lowlighter/metrics@latest
        name: Stargazers
        with:
          user: fallgozxtest
          template: classic
          filename: metrics-stargazers.svg
          plugin_stargazers: yes
          plugin_stargazers_charts: yes
          output_action: commit
          committer_branch: main
          committer_message: 'chore: update stargazers metrics [Skip GitHub Action]'
          token: ${{ secrets.METRICS_TOKEN }}
      - uses: lowlighter/metrics@latest
        name: Lines of code
        with:
          user: fallgozxtest
          template: classic
          filename: metrics-lines.svg
          plugin_lines: yes
          plugin_lines_sections: lines, commits, contributions
          output_action: commit
          committer_branch: main
          committer_message: 'chore: update lines metrics [Skip GitHub Action]'
          token: ${{ secrets.METRICS_TOKEN }}
      - uses: lowlighter/metrics@latest
        name: Trophies / achievements
        with:
          user: fallgozxtest
          template: classic
          filename: metrics-achievements.svg
          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_achievements_threshold: C
          output_action: commit
          committer_branch: main
          committer_message: 'chore: update achievements metrics [Skip GitHub Action]'
          token: ${{ secrets.METRICS_TOKEN }}
