name: Metrics
on:
  push:
    branches: [ main, master ]
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

permissions:
  contents: write
  issues: write

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          user: fallgozxtest
          template: classic
          output: github-metrics.svg
          filename: github-metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}
      - uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: gh-pages
          build_dir: ./
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
