name: Metrics
on:
  push:
    branches: [ main, master ]
    paths-ignore:
      - '*.svg'
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

permissions:
  contents: write
  issues: write

jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        name: Languages metrics
        with:
          user: fallgozxtest
          template: terminal
          plugin_languages: yes
          plugin_languages_indepth: yes
          plugin_habits: yes
          plugin_habits_charts: yes
          output_action: commit
          committer_branch: metrics
          committer_message: 'chore: update metrics [Skip GitHub Action]'
          token: ${{ secrets.METRICS_TOKEN }}
      - uses: lowlighter/metrics@latest
        name: Isometric calendar
        with:
          user: fallgozxtest
          template: classic
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          output_action: commit
          committer_branch: metrics
          committer_message: 'chore: update isometric calendar [Skip GitHub Action]'
          token: ${{ secrets.METRICS_TOKEN }}
          filename: github-metrics-isocalendar.svg
      - uses: lowlighter/metrics@latest
        name: Stargazers
        with:
          user: fallgozxtest
          template: classic
          plugin_stargazers: yes
          plugin_stargazers_charts: yes
          output_action: commit
          committer_branch: metrics
          committer_message: 'chore: update stargazers [Skip GitHub Action]'
          token: ${{ secrets.METRICS_TOKEN }}
          filename: github-metrics-stargazers.svg
      - uses: lowlighter/metrics@latest
        name: Lines of code
        with:
          user: fallgozxtest
          template: classic
          plugin_lines: yes
          plugin_lines_sections: lines, commits, contributions
          output_action: commit
          committer_branch: metrics
          committer_message: 'chore: update lines of code [Skip GitHub Action]'
          token: ${{ secrets.METRICS_TOKEN }}
          filename: github-metrics-lines.svg
